import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Real-Time EEG-to-Text Training Architecture\n",
                "\n",
                "This notebook implements the real-time EEG-to-Text models based on state-of-the-art Voice-to-Text ASR techniques.\n",
                "\n",
                "## Models Included:\n",
                "1. **Conformer (Convolution-augmented Transformer)**: The gold standard for ASR. It uses 1D spatial convolutions for feature extraction, followed by Conformer blocks to capture both local micro-states (CNN) and global sequence intent (Transformer).\n",
                "2. **CNN-LSTM (DeepSpeech style)**: A classical approach for sequential signal processing.\n",
                "\n",
                "**Loss Function**: Connectionist Temporal Classification (CTC) for alignment-free training.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Requirements: pip install torch torchaudio h5py matplotlib\n",
                "import os\n",
                "import glob\n",
                "import h5py\n",
                "import numpy as np\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "import torch.optim as optim\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "import torchaudio\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "DATASET_PATH = r'C:\\SDE Projects\\Open-BCI-EEG-Waves-To-Text-Translation-And-further-Robotic-Implementaions\\dataset\\extracted'\n",
                "MODELS_DIR = 'models'\n",
                "METRICS_DIR = 'metrics'\n",
                "\n",
                "os.makedirs(MODELS_DIR, exist_ok=True)\n",
                "os.makedirs(METRICS_DIR, exist_ok=True)",
            ],
        },
        {"cell_type": "markdown", "metadata": {}, "source": ["## 1. Dataset Loading"]},
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class EEGDataset(Dataset):\n",
                "    def __init__(self, data_dir, max_len=500):\n",
                "        self.files = glob.glob(os.path.join(data_dir, '**', '*.h5'), recursive=True)\n",
                "        self.max_len = max_len\n",
                "        # Simple vocabulary character-level mapping\n",
                '        self.chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,!?\'-"\n',
                "        self.char_to_idx = {ch: i+1 for i, ch in enumerate(self.chars)}\n",
                "        self.char_to_idx['<PAD>'] = 0\n",
                "        self.vocab_size = len(self.char_to_idx)\n",
                "        \n",
                "    def __len__(self):\n",
                "        return len(self.files)\n",
                "        \n",
                "    def __getitem__(self, idx):\n",
                "        file_path = self.files[idx]\n",
                "        filename = os.path.basename(file_path)\n",
                "        transcript = filename.replace('.h5', '').replace('_', ' ')\n",
                "        \n",
                "        with h5py.File(file_path, 'r') as f:\n",
                "            keys = list(f.keys())\n",
                "            if len(keys) > 0:\n",
                "                eeg_data = f[keys[0]][:]  # shape expected: [105 channels, time_steps]\n",
                "            else:\n",
                "                eeg_data = np.zeros((105, self.max_len))\n",
                "                \n",
                "        if eeg_data.shape[1] < self.max_len:\n",
                "            pad_width = self.max_len - eeg_data.shape[1]\n",
                "            eeg_data = np.pad(eeg_data, ((0, 0), (0, pad_width)), mode='constant')\n",
                "        else:\n",
                "            eeg_data = eeg_data[:, :self.max_len]\n",
                "            \n",
                "        # [time_steps, channels]\n",
                "        eeg_tensor = torch.tensor(eeg_data, dtype=torch.float32).transpose(0, 1)\n",
                "        \n",
                "        target = [self.char_to_idx.get(c, 0) for c in transcript]\n",
                "        target_tensor = torch.tensor(target, dtype=torch.long)\n",
                "        \n",
                "        return eeg_tensor, target_tensor\n",
                "\n",
                "dataset = EEGDataset(DATASET_PATH)\n",
                'print(f"Found {len(dataset)} HDF5 files for training.")',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Models Definition\n",
                "### 2.1 Conformer (Convolution-augmented Transformer)\n",
                "State-of-the-art ASR model adapted for EEG spatial decoding.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from torchaudio.models import Conformer\n",
                "\n",
                "class ConformerEEG(nn.Module):\n",
                "    def __init__(self, num_channels=105, input_dim=256, num_classes=65):\n",
                "        super(ConformerEEG, self).__init__()\n",
                "        # Spatial Convolution to map 105 channels to internal representation\n",
                "        self.spatial_conv = nn.Conv1d(num_channels, input_dim, kernel_size=3, padding=1)\n",
                "        \n",
                "        # Torchaudio Conformer expects inputs of (batch, time, input_dim)\n",
                "        self.conformer = Conformer(\n",
                "            input_dim=input_dim,\n",
                "            num_heads=4,\n",
                "            ffn_dim=512,\n",
                "            num_layers=4,\n",
                "            depthwise_conv_kernel_size=31\n",
                "        )\n",
                "        \n",
                "        # Linear head for character prediction (CTC)\n",
                "        self.fc = nn.Linear(input_dim, num_classes)\n",
                "        \n",
                "    def forward(self, x):\n",
                "        # x shape: [batch, time, channels]\n",
                "        x = x.transpose(1, 2) # [batch, channels, time]\n",
                "        x = self.spatial_conv(x) # [batch, input_dim, time]\n",
                "        x = x.transpose(1, 2) # [batch, time, input_dim]\n",
                "        \n",
                "        # Conformer requires input lengths, using max length for simplicity\n",
                "        lengths = torch.full((x.size(0),), x.size(1), dtype=torch.long, device=x.device)\n",
                "        \n",
                "        out, _ = self.conformer(x, lengths)\n",
                "        out = self.fc(out) # [batch, time, num_classes]\n",
                "        return out",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["### 2.2 DeepSpeech-style (CNN-LSTM)"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class DeepSpeechEEG(nn.Module):\n",
                "    def __init__(self, num_channels=105, hidden_size=256, num_classes=65):\n",
                "        super(DeepSpeechEEG, self).__init__()\n",
                "        self.conv1 = nn.Conv1d(num_channels, 64, kernel_size=5, stride=1, padding=2)\n",
                "        self.bn1 = nn.BatchNorm1d(64)\n",
                "        self.relu = nn.ReLU()\n",
                "        self.pool = nn.MaxPool1d(2)\n",
                "        \n",
                "        self.lstm = nn.LSTM(64, hidden_size, num_layers=2, batch_first=True, bidirectional=True)\n",
                "        self.fc = nn.Linear(hidden_size * 2, num_classes)\n",
                "        \n",
                "    def forward(self, x):\n",
                "        x = x.transpose(1, 2)\n",
                "        x = self.pool(self.relu(self.bn1(self.conv1(x))))\n",
                "        x = x.transpose(1, 2)\n",
                "        \n",
                "        self.lstm.flatten_parameters()\n",
                "        out, _ = self.lstm(x)\n",
                "        out = self.fc(out)\n",
                "        return out",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 3. Training Loop (CTC Loss)"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def train_model(model, name, dataloader, epochs=5):\n",
                "    criterion = nn.CTCLoss(blank=0, zero_infinity=True)\n",
                "    optimizer = optim.Adam(model.parameters(), lr=1e-3)\n",
                "    \n",
                "    loss_history = []\n",
                "    model.train()\n",
                "    for epoch in range(epochs):\n",
                "        epoch_loss = 0\n",
                "        for eeg, target in dataloader:\n",
                "            batch_size = eeg.size(0)\n",
                "            # Pooling in DeepSpeech halves the time dimension\n",
                "            out_time = eeg.size(1)//2 if isinstance(model, DeepSpeechEEG) else eeg.size(1)\n",
                "            input_lengths = torch.full(size=(batch_size,), fill_value=out_time, dtype=torch.long)\n",
                "            target_lengths = torch.tensor([len(target[0])])\n",
                "            \n",
                "            optimizer.zero_grad()\n",
                "            out = model(eeg)\n",
                "            out = out.transpose(0, 1) # [time, batch, classes]\n",
                "            out = nn.functional.log_softmax(out, dim=2)\n",
                "            \n",
                "            loss = criterion(out, target, input_lengths, target_lengths)\n",
                "            loss.backward()\n",
                "            optimizer.step()\n",
                "            \n",
                "            epoch_loss += loss.item()\n",
                "            \n",
                "        avg_loss = epoch_loss / max(1, len(dataloader))\n",
                "        loss_history.append(avg_loss)\n",
                '        print(f"[{name}] Epoch {epoch+1}/{epochs} | Loss: {avg_loss:.4f}")\n',
                "        \n",
                "    torch.save(model.state_dict(), os.path.join(MODELS_DIR, f'{name}_checkpoint.pth'))\n",
                "    return loss_history\n",
                "\n",
                "dataloader = DataLoader(dataset, batch_size=1, shuffle=True)\n",
                "\n",
                "if len(dataset) > 0:\n",
                "    vocab_size = dataset.vocab_size\n",
                "    \n",
                '    print("Training ConformerEEG...")\n',
                "    conf_model = ConformerEEG(num_classes=vocab_size)\n",
                '    conf_losses = train_model(conf_model, "ConformerEEG", dataloader, epochs=5)\n',
                "    \n",
                '    print("Training DeepSpeechEEG...")\n',
                "    ds_model = DeepSpeechEEG(num_classes=vocab_size)\n",
                '    ds_losses = train_model(ds_model, "DeepSpeechEEG", dataloader, epochs=5)\n',
                "    \n",
                "    plt.figure(figsize=(10,5))\n",
                "    plt.plot(conf_losses, label='Conformer Loss', marker='o')\n",
                "    plt.plot(ds_losses, label='DeepSpeech Loss', marker='x')\n",
                "    plt.title('Training Loss over Epochs')\n",
                "    plt.xlabel('Epoch')\n",
                "    plt.ylabel('CTC Loss')\n",
                "    plt.legend()\n",
                "    \n",
                "    plot_path = os.path.join(METRICS_DIR, 'training_loss_curves.png')\n",
                "    plt.savefig(plot_path)\n",
                '    print(f"Saved metrics plot to {plot_path}")\n',
                "    plt.show()\n",
                "else:\n",
                '    print("No HDF5 data found. Check DATASET_PATH.")',
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

with open("training/train_eeg.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
print("Updated training/train_eeg.ipynb successfully.")
